Hw04 lru cache
iKOPKACtraxa/otus-hw pull request #5
Opened 2021-03-31 19:48 UTC by iKOPKACtraxa

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-04-01 16:59 UTC, balabanovds requested changes
Хорошая работа. Информативные комментарии - так держать!
Есть замечания и не увидел теста на логику выталкивания из кэша редко используемых элементов.

Пока возвращаю на доработку.

https://otus.ru/teacher-lk/homework/156446/9789/

2021-04-01 16:59 UTC, balabanovds commented on hw04_lru_cache/list.go
> +// NewList создает новый *list в интерфейсе List.
удобно, когда конструктор после объявления типа, который он возвращает
и может его неэкспортированным сделать (все ж это внутренняя реализация)?

2021-04-01 16:59 UTC, balabanovds commented on hw04_lru_cache/list.go
> +// bindToBack привязывает элемент в начале списка, симметричен bindToFront.
кажется тут опечатка

2021-04-01 16:59 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +// NewCache создает новый *lruCache в интерфейсе Cache.
Вы пишете либу, которой кто-то будет пользоваться. А если невалидные данные пришли?

P.S. сигнатуру функции можно менять.. :)

2021-04-01 16:59 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	cacheItem := cacheItem{
эмм.. а зачем Вы его создаете?

2021-04-01 19:54 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
> +	cacheItem := cacheItem{
Если вопрос про cacheItem, то тут я руководствовался следующим:
1) Он был изначально в задании
2) При решении ДЗ два человека уточнили, а зачем он нужен, если и без него все работает. Алексей Бакин посоветовал перечитать задание)
3) Я внимательно прочитал задание и единственное, что говорило о том, что его нужно применять было
"Элемент кэша хранит в себе ключ, по которому он лежит в словаре, и само значение.
Для чего это нужно понятно из алгоритма работы кэша (см. ниже)." (далее ниже алгоритм Get и Set)
4) Я делаю вывод, что этот cacheItem нужно применять в методах.
5) В принципе, он там не обязателен, можно просто брать аргументы функции
6) Скорее всего cacheItem это просто контейнер, для удобства чтения кода и какой-то инкапсуляции. Типа, функция получила аргументы, запаковываем в cacheItem и потом его используем в алгоритме.

2021-04-01 19:55 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
> +// NewCache создает новый *lruCache в интерфейсе Cache.
Денис, я не очень понял смысл, можете перефразировать? Вопрос в том, что будет если кто-то захочет в кеш положить что-то невалидное? Так, я так понял, туда можно вообще все что хочешь класть, int string в любом порядки и сочетаниях. Главное, чтобы объект клали один и у него было название (ключ string).

И что значит "сигнатуру функции можно менять" =)
Сигнатура, в моем понимании - это имя функции, то что она принимает int и выдает интерфейс. Зачем и как ее можно изменить?

2021-04-01 20:40 UTC, iKOPKACtraxa commented on hw04_lru_cache/list.go
> +// NewList создает новый *list в интерфейсе List.
Учел в след коммите.

2021-04-01 20:41 UTC, iKOPKACtraxa commented on hw04_lru_cache/list.go
> +// bindToBack привязывает элемент в начале списка, симметричен bindToFront.
да опечатка, спасибо, учел в следующем коммите.
bindToBack привязывает элемент в конце списка

2021-04-02 04:59 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +// NewCache создает новый *lruCache в интерфейсе Cache.
сигнатура функции - имя, аргументы, что она возвращает, а также ее видимость
```go
func foo() {}
func Foo() {} // разные сигнатуры

func foo() int {}
func foo() (int, bool) {} // разные сигнатуры
```

Теперь перефразирую проблему - есть ли смысл в кеше с 0 емкостью или даже с отрицательной? 🙂

2021-04-02 05:13 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	cacheItem := cacheItem{
ну вообще cacheItem нужен чтобы не создавать доп структур типа `map[*ListItem]Key`
подешевле выходит.
подумайте как сделать так чтобы избавиться от `map[*ListItem]Key` 😉

2021-04-02 17:29 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
> +// NewCache создает новый *lruCache в интерфейсе Cache.
Проверяем, входящий capacity int на значение больше нуля, понятно.
А зачем сигнатуру менять? Например, чтобы не int использовать, а uint? Я сначала начал так делать, но потом посмотрел на стандартный func len(v Type) int, и задумался.

2021-04-02 17:32 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
> +	cacheItem := cacheItem{
Поонял)) Это будет самый старый элемент, чтобы его удалять и на его место писать новую жертву)

2021-04-04 08:16 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
> +	cacheItem := cacheItem{
Догадался до верного решения, cahceItem это item с ключем, его и кладем в очередь

2021-04-04 19:17 UTC, balabanovds approved these changes
Хорошо справились.
Отписал по сигнатуре конструктора.
Также тест "purge logic2" не очень похож на тест на выдавливание редко-используемых аргументов.

Пока оценка 8/10

2021-04-04 19:17 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +// NewCache создает новый *lruCache в интерфейсе Cache.
лучше явно возвращать ошибку, причем именованную, чтобы потом можно было ее проверять

2021-04-06 20:06 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
> +// NewCache создает новый *lruCache в интерфейсе Cache.
понял, сделал явную ошибку через:
`var ErrInvalidCapacity = errors.New("invalid capacity: <= 0")`
`func NewCache(capacity int) (Cache, error) {
	if capacity > 0 {
		return &lruCache{
			capacity: capacity,
			queue:    NewList(),
			items:    make(map[Key]*ListItem, capacity),
		}, nil
	}
	return nil, ErrInvalidCapacity`

2021-04-06 20:15 UTC, iKOPKACtraxa commented
> Хорошо справились.
> Отписал по сигнатуре конструктора.
> Также тест "purge logic2" не очень похож на тест на выдавливание редко-используемых аргументов.
> 
> Пока оценка 8/10

"purge logic2" писал ровно по README:
>  на логику выталкивания давно используемых элементов
> (например: n = 3, добавили 3 элемента, обратились несколько раз к разным элементам:
> изменили значение, получили значение и пр. - добавили 4й элемент,
> из первой тройки вытолкнется тот элемент, что был затронут наиболее давно).
я создал кеш на 3 элемента, добавил aaa bbb ccc, поабдейтил их, при этом ааа получился самым старым, добавляю 4-й элемент ddd, проверяю, что ааа вылетел и оставшиеся верные (комментарии расставил в тесте)

2021-04-06 20:17 UTC, iKOPKACtraxa commented
Запушил новую версию, спасибо за замечания!
Просьба проверить изменения.

2021-04-11 20:02 UTC, balabanovds approved these changes
Отлично 10/10

2021-04-12 04:33 UTC, merged