Hw05 parallel execution
iKOPKACtraxa/otus-hw pull request #6
Opened 2021-04-11 14:10 UTC by iKOPKACtraxa

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-04-12 06:01 UTC, kulti requested changes
Мы с вами уже обсуждали разные решения этого ДЗ. Стало намного лаконичнее, чем было изначально 👍 

Еще есть над чем поработать. Думаю, в коде даже есть ошибка (второе вычитывание из toWorkerCh).

2021-04-12 06:01 UTC, kulti commented on hw04_lru_cache/cache.go
>  package hw04lrucache
Эти файлы из другого ДЗ. Уберите их, пожалуйста, из этой ветки.

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +func TestRunAdditional(t *testing.T) {
Непонятное название тестов. Не понимаю, что этот табличный тест должен тестировать. Очень похож на те тесты, что уже есть.

Выглядит так, что это проверкой той же самой логики, что и в изначальных тестах, но с другими значениями. Тогда это не новые тесты, а лишние тесты.

Если это не так, то надо сделать понятные название:
1. Назвать этот тест понятным именем.
2. При необходимости дать каждому сабтесту дать понятное название.

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		// далее тесты при m<=0: трактуется как игнорировать ошибки
Эти комментарии в коде вредные. Главная проблема комментариев в коде в том, что код меняется, а комментарии нет — комментарии начинают врать и сбивать с толку. Лучше выражать те же самые идеи в коде.

Например, тут можно  дать названия тестам. И станет очевидно, что из всех кейсов новый только один, когда m <=0. Т.е. тут только один новый тест, остальные — лишние.

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run.go
> +				if ok {
Посмотрите еще раз кусочек занятия про горутины и каналы (можно просто слайды). Там показано, как лаконичнее написать логику чтения из канала пока в нем есть значения.

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run.go
> +					mutex.Unlock()
Эти постоянные разрозненные mutex.Lock, mutex.Unlock —  короткий путь отстрелить себе ногу и забыть где-нибудь что-нибудь разлочить.

Можно инкапсулировать логику синхронного доступа в новом типе. В данном случае это будет структура со счетчиком + мьютекс. Либо использовать другой подход — тут можно использовать atomic (будут рассказывать на второй части занятия про примитивы синхронизации).

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run.go
> +		if totalErrors < m || m <= 0 {
Если totalErrors будет >= m, то вы этом цикле будет постоянно браться и отпускаться мьютекс. Зачем эта лишняя работа?

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run.go
> +					mutex.Unlock()
Я понял, что этот мьютекс еще защищает errToReturn. Это еще одна проблема текущего подхода — непонятно, что защищает мьютекс :) Если бы был отдельный тип, то все было бы понятно. Но тут все равно лучше атомик использовать, а errToReturn вообще лишняя сущность.

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Вот эта строчка для меня выглядит загадочно и опасно. Воркер уже читал из канала на этой итерации. Зачем-то читает еще раз перед выходом. Очень сомнительно — думаю, в этот канал могут больше ничего не записать и воркер просто зависнет навсегда.

2021-04-12 06:01 UTC, kulti commented on hw05_parallel_execution/run.go
> +	errToReturn := error(nil)
Можно такие переменные так определять: `var errToReturn error`. Вроде, так логичнее выглядит.

2021-04-12 17:52 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
>  package hw04lrucache
1) У меня только догадка, откуда это взялось. По-видимому при работе над разными ДЗ нужно делать переключение git  checkout правильно. Я вроде бы делал переключение, но не перед изменениями в файлах с соответствующей домашкой, а перед коммитами. Видимо, нужно переключаться на нужную ветку перед изменением в файлах, а не перед коммитами?
2) Как можно убрать их из этой ветки?
3) Еще после merge 3 ДЗ при открытом PR в 4 (например) GH мне предлагает вмержить изменения из обновленного master (с вмерженным 3 ДЗ) в 4 ДЗ. Я соглашался, верно делал? или лучше не соглашаться, все равно ДЗ разные и обновляют master независимо.

2021-04-12 18:03 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +	errToReturn := error(nil)
Можно, просто сделал чтобы не выделялось относительно предыдущей строки.
totalErrors := 0
errToReturn := error(nil)
поменял на 
var totalErrors int
var errToReturn error

2021-04-12 18:13 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Эта строка нужна только для того, чтобы прочитать последние задачи из канала, чтобы освободить код в 50 строке. Если избавляться от этого вычитывания ненужных задач, то нужно переписать логику for-а на 46-54 строках.

2021-04-12 18:47 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +					mutex.Unlock()
Сначала я тоже подумал про отдельную структуру с mutex, но мотом мне понравилось, что можно защитить код Lock/Unlock без создания структур, налету, и я так и решил сделать. Но потом понял, что нужно защищать переменную в if и тогда мой mutex так некрасиво расползся. Да еще к тому же, errToReturn, нужно было защитить, так как он может конкурентно изменяться воркерами.
Я пока не знаю про атомик, только общее представление (по видимому это сущность, защищенная от datarace), попробую применить его.
Теперь про errToReturn. Думаю, можно удалить это присвоение в воркере и потом просто прочитать количество ошибок totalErrors перед выходом из Run и выдать нужный return.

2021-04-12 18:49 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +		if totalErrors < m || m <= 0 {
Это костыль для защиты totalErrors от datarace. Как было указано выше, попробую atomic.

2021-04-12 18:51 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run_test.go
> +func TestRunAdditional(t *testing.T) {
> Непонятное название тестов. Не понимаю, что этот табличный тест должен тестировать. Очень похож на те тесты, что уже есть.
оаоаоаоа

2021-04-12 18:51 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run_test.go
> +func TestRunAdditional(t *testing.T) {
> Непонятное название тестов. Не понимаю, что этот табличный тест должен тестировать. Очень похож на те тесты, что уже есть.

в

2021-04-12 18:54 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run_test.go
> +func TestRunAdditional(t *testing.T) {
> Непонятное название тестов. Не понимаю, что этот табличный тест должен тестировать. Очень похож на те тесты, что уже есть.

Часть тестов пересекается, решил, что изменять существующие тесты не корректно, поэтому просто дописал свои более широкие тесты, которые частично включают логику сущестующих тестов. Мне показалось много тестов не бывает, даже если пара повторится, то хуже от этого не будет)
Переименую тесты и сабтесты.

2021-04-12 18:55 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run_test.go
> +		// далее тесты при m<=0: трактуется как игнорировать ошибки
Понял, переименую и скорректирую.

2021-04-12 19:29 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +					mutex.Unlock()
atomic просто огонь)
errToReturn удалил сделав простой if в конце, там datarace не ожидается, все горутины остановлены.

2021-04-12 19:32 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +		if totalErrors < m || m <= 0 {
atomic - наше все! (почти))

2021-04-12 20:40 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +				if ok {
Да, помнил про range по каналу, но я от него отказался, так как мне зачем-то понадобился именно ok, так как был какой-то код в else (а не просто return). Сейчас нет причин для лишнего кода, конечно, переделал на range по каналу.

2021-04-13 19:14 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run_test.go
> +func TestRunAdditional(t *testing.T) {
Удалил явные дубли тестов.

2021-04-13 19:24 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Оставил комментарий в коде

2021-04-13 19:28 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run_test.go
> +		// далее тесты при m<=0: трактуется как игнорировать ошибки
Удалил, действительно дублируются зря.

2021-04-14 05:20 UTC, kulti commented on hw04_lru_cache/cache.go
>  package hw04lrucache
Владимир, разработчику важно уметь работать с git'ом. Если есть трудности с пониманием, то надо отдельно поизучать этот инструмент. К сожалению, ничего фундаментального посоветовать не могу. Мне нравится вот эта статья с визуализацией команд — https://dev.to/lydiahallie/cs-visualized-useful-git-commands-37p1. Мне кажется она хорошо объясняет, как коммиты и ветки взаимодействуют.
 
 Для сдачи ДЗ рекомендую каждую ветку бранчевать от мастера. Тут, похоже был сделан бранч от ветки с hw4.
 
 Сейчас можно сделать ребезй ветки hw5 на мастер (т.к. hw4 замержен уже). Вроде GН именно это и предлагает. Либо Interactive Rebase (в статье есть про него) и дропнуть коммит с hw4.

2021-04-14 05:28 UTC, kulti commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Комментарии не решают проблем в коде. Обычно они их только добавляют :) Т.к. устаревают и начинаю врать.

Это чтение и выход выглядят непонятно и опасно. Думаю, тут даже баг есть. Например, в tasks 2 задачи, у нас два воркера, каждый взял по задаче. Обе задачи завершились с ошибкой и произошел выход за лимит ошибок. В канал toWorkerCh ничего писать уже не будут и горутины-воркеры зависнут навсегда.

Предлагаю подумать, так ли уж нужен выход в этом месте выход из воркера.

2021-04-14 05:32 UTC, kulti requested changes
Решение стало намного лучше. Уже почти все готово.

1. Нужно убрать лишние файлы.
2. Пофиксить баг https://github.com/iKOPKACtraxa/otus-hw/pull/6#discussion_r612946306

2021-04-14 05:32 UTC, kulti commented on hw05_parallel_execution/run.go
> +		}
Этот if+else можно написать проще:
```
if m > 0 && int(atomic.LoadInt32(&totalErrors)) >= m {
  break
}
toWorkerCh <- task
```

2021-04-14 05:32 UTC, kulti commented on hw05_parallel_execution/run.go
> +	if int(totalErrors) >= m && m > 0 {
Поставил 👍 под рассуждениями, почему тут не нужен атомик. На всякий случай продублирую, вдруг не увидите, т.к. тот дискашен зарезолвлен :)

2021-04-16 21:36 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
>  package hw04lrucache
Доброй ночи!
Этот коммит нельзя удалять, он относится к прошлому PR, если зайти в прошлый (закрытый PR) то можно там его увидеть.
При этом в текущем PR если нажать на этот коммит, то видно что он принадлежит к ветке master (то есть уже merged). Это видимо какой-то глюк GH, где-то я его сломал) Rebase делать не стал, боюсь удалится вся история по исправлению кода и комментарии.
Еще заметил, что если удалить папку локально и сделать clone то скачивается только ветка мастера, без бранчей, странное поведение, ожидал, что после клонирования можно будет переключаться между ветками. Если склонировать через desctop версию, то нормально копируется, с бранчем и можно переключаться между ветками уже в терминале.

2021-04-16 21:41 UTC, iKOPKACtraxa commented on hw04_lru_cache/cache.go
>  package hw04lrucache
Вот [тут](https://qna.habr.com/q/112819) ответ, почему git clone не копирует ветки (вернее копирует, но не делает их отслеживаемыми). Видимо десктопная версия делает это автоматом.

2021-04-17 07:23 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +	if int(totalErrors) >= m && m > 0 {
С этими резолвами, хотелось бы прояснить, закрывать их должны вы по идее как инициатор?
Пример, вы выставляете замечание, я его отрабатываю, но, по идее, не должен его резолвить, даже если замечание снято (как мне может показаться). Вы резолвите если ок или оставляете комментарий.
Или я например задаю вопрос по коду, вы отвечате, когда для меня все ОК, я делаю резолв.

В общем подход такой, резолвит тот кто начал conversation, верно?

2021-04-17 07:31 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +		}
Абсолютно согласен) Сделал.

2021-04-17 08:09 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Вот горутина (два экземпляра для нашего примера) которая зависла на этом вычитывании:
```go
		go func() { // Горутина i-го работника, который выполняет Task()
			defer wg.Done()
			for task := range toWorkerCh {
				err := task()
				if err != nil {
					atomic.AddInt32(&totalErrors, 1)
				}
				if int(atomic.LoadInt32(&totalErrors)) >= m && m > 0 {
					<-toWorkerCh // чтение последней записи из канала, чтобы освободить код на стороне записи
					return
				}
			}
		}()
```
Ниже не в горутине, а в основной функции Run такой код:
```go
	for _, task := range tasks {
		if m > 0 && int(atomic.LoadInt32(&totalErrors)) >= m {
			break
		}
		toWorkerCh <- task
	}
	close(toWorkerCh)
```
Моделируем зависание горутин: те две горутины получили два error и увеличили счетчик ошибок, он теперь либо равен лимиту либо больше (если, например, воркеров было n и все они получили ошибку) и все они зависли на чтении канала.
Код который показан вторым куском итерирует по слайсу и отправляет задачи в канал, на одной из итерации он получает условие для break (лимит ошибок превышен) и выходит из итераций. Сразу после этого идет close канала, так горутины которые зависли получат ZV и пойдут в return.

Решение рабочее, но продолжим рассуждение, в двух вариантах: 1) что будет, если удалить строчку с вычитыванием, 2) У нас есть закрытие канала, его можно получать и обрабатывать в воркерах как сигнал на выход.

1) Если мы удалим вычитывание то скорее всего зависнет код из второго блока, например два воркера получили ошибки вышли за лимит и ушли в return. Второй блок в это время ждет, когда кто-то получит таск, но никогда его не отдаст, так как все воркеры уйдут. Тест показал, что прога зависла.
2) так не получится, код во втором блоке всегда ждет, когда будет взята последняя задача

2021-04-17 08:20 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Есть еще идея, напишу...

2021-04-17 10:26 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Вот убираем if с return в воркере:
```go
		go func() { // Горутина i-го работника, который выполняет Task()
			defer wg.Done()
			for task := range toWorkerCh {
				err := task()
				if err != nil {
					atomic.AddInt32(&totalErrors, 1)
				}
				// if int(atomic.LoadInt32(&totalErrors)) >= m && m > 0 {
				// 	<-toWorkerCh // чтение последней записи из канала, чтобы освободить код на стороне записи
				// 	return
				// }
			}
		}()
```
Этот return произойдет автоматически при закрытом канале toWorkerCh. А вот как изменился второй блок:
```go
	for _, task := range tasks {
		if int(atomic.LoadInt32(&totalErrors)) < m || m <= 0 {
			toWorkerCh <- task
		} else {
			break
		}
	}
	close(toWorkerCh)
```
Прикол в том, что пришлось вернуть этот else, который я для упрощения удалял [тут](https://github.com/iKOPKACtraxa/otus-hw/pull/6#discussion_r612946846)

2021-04-17 11:27 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +						<-toWorkerCh
Done!

2021-04-17 11:27 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +		}
Как оказалось, напрасно)

2021-04-18 06:12 UTC, kulti commented on hw05_parallel_execution/run.go
> +	if int(totalErrors) >= m && m > 0 {
Мне больше нравиться подход — резолвит тот, кто создал дискашен. Человек что-то имел в виду и, как вы верно заметили, другому человеку может казаться, что он именно это и сделал, а по факту совсем другое или неполностью.

У нас тут нет строгих правил, мы изучаем Go, а не работу в команде :) Так что можете делать так, как вам удобнее. Я разберусь :)

2021-04-18 06:17 UTC, kulti commented on hw04_lru_cache/cache.go
>  package hw04lrucache
Всегда удивлялся, почему люди боятся что-то сломать в git'e. Надо поискать в справочнике фобий, наверняка уже какую-нибудь гитофобию записали в него 😅 Я ломал, потом разбирался, учился работать с инструментом. Сейчас пользуюсь с удовольствием :)

Аппрувить МР с этими изменениями странно, т.к. МР по пятой ДЗ, а тут что-то еще.

Предлагаю все-таки разобраться с гитом. Если боитесь сломать, то можем вместе сделать нужные изменения. Я подскажу, как делать все безопасно, и даже если все пойдет не по плану, можно будет легко вернуться к тому, что было. Напишите мне в слаке, выберем время.

2021-04-18 06:20 UTC, kulti commented on hw05_parallel_execution/run.go
> +		}
Интересно почему? Код полностью эквивалентный.

2021-04-18 12:39 UTC, iKOPKACtraxa commented on hw05_parallel_execution/run.go
> +		}
Согласен)) Я думал, что код зависнет на записи в канал. Но этого не произойдет, так как воркеры вычитывают все пока канал не закроется.

2021-04-18 15:54 UTC, iKOPKACtraxa commented
Спасибо большое, Алексей, за помощь!

2021-04-18 15:58 UTC, kulti approved these changes
Принято! 10/10

2021-04-18 16:19 UTC, merged