Hw06 pipeline execution
iKOPKACtraxa/otus-hw pull request #7
Opened 2021-04-18 16:29 UTC by iKOPKACtraxa

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-04-23 06:11 UTC, kulti requested changes
Хорошее, компактное решение. Круто, что подумали про вариант done == nil. Есть один нюанс, о котором стоит хорошенько подумать. Если что, пишите в слак.

2021-04-23 06:11 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +	for _, stage := range stages {
Как думаете, что будет с этим циклом, если `len(stages) == 0`?

2021-04-23 06:11 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +					newIn <- val
Любое чтение/запись без select'a выглядит, как то, что может зависнуть навсегда. Здесь два таких места. Предлагаю подумать на эту тему.

2021-04-26 18:59 UTC, iKOPKACtraxa commented on hw06_pipeline_execution/pipeline.go
> +	for _, stage := range stages {
Этот цикл не запустится. Таким образом не будет использоваться done канал и in никогда не закроется.
Нужно продумать эту логику? Если да, то я вместо простого in могу вернуть chanCloser(in, done).

2021-04-26 20:10 UTC, iKOPKACtraxa commented on hw06_pipeline_execution/pipeline.go
> +					newIn <- val
Я понял, вместо этого
```go
			for {
				val := <-in
				select {
				case <-done:
					close(newIn)
					return
				default:
					newIn <- val
				}
			}
```
лучше сделать по шаблону повышения приоритета канала done + защиту каналов чтения (а потом записи) каналом done:
```go
			defer close(newIn)
			for {
				select {
				case <-done:
					return
				default:
					select {
					case <-done:
						return
					case val := <-in:
						select {
						case <-done:
							return
						case newIn <- val:
						}
					}
				}
			}
```

2) Вопрос: правильно понимаю, что вместо постоянного создания новой переменной val := лучше создать ее один раз (как я выше написал var val interface{}) и постоянно переиспользовать, это будет экономить ресурсы памяти? (Помню, помню, можно не заморачиваться, если не доказано, что данная оптимизация существенно улучшит скорость. Но с другой стороны, если не париться и везде писать неэффективно "по-привычке" то потом придется все переписывать и лопатить весь код, выискивая, где же самые неэффективные места? Мне кажется проще изначально писать лучше, если это не занимает много времени.

2021-04-28 16:14 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +	for _, stage := range stages {
Этот in закрывает тот, кто его передал :) Обернуть входной in — хорошая идея 👍 

Я о том, что цикл не сделает ни одной итерации и вернется входной in. Тоже самое происходит при проверке len(stages) == 0 —  возвращается входной in. Т.е. проверка длинны тут не нужна :)

2021-04-28 16:21 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +					newIn <- val
> лучше сделать по шаблону повышения приоритета канала done + защиту каналов чтения (а потом записи) каналом done
Насчет приоритезации не уверен на 100%, что от нее тут толк будет, но лишней она точно не будет. А вот защита селектом точно нужна 👍 

> вместо постоянного создания новой переменной val := лучше создать ее один раз
Хороший вопрос. Думаю, что это почти ничего не сэкономит, т.к. переменная будет на стеке. Это даже не микро-оптимизация, а нано-оптимизация. И да, лучше это проверить бенчмарком, если очень хочется :)

> Мне кажется проще изначально писать лучше, если это не занимает много времени.
Совершенно верное замечание. Полностью поддерживаю. Просто я говорю, что не парьтесь раньше времени в первую очередь для любителей преждевременной оптимизации, которые как раз тратят кучу времени на то, что, возможно, не нужно делать.

2021-05-10 21:18 UTC, iKOPKACtraxa commented on hw06_pipeline_execution/pipeline.go
> +	for _, stage := range stages {
Согласен абсолютно, данная проверка на len совершенно не нужна, помню, что когда я ее добавлял она мне казалось просто необходимой, но сейчас, конечно, она избыточна.

2021-05-11 15:34 UTC, kulti approved these changes
Теперь все 👌 ДЗ принято — 10/10.

2021-05-11 18:56 UTC, merged